version: "3.8"

services:
  mssql:
    build:
      context: ./mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    volumes:
      - sqldata:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup
      - ./mssql/init-scripts:/var/opt/mssql/init-scripts
    ports:
      - "${MSSQL_PORT}:1433"
    networks:
      - backend
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT 1" || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

  admin:
    build:
      context: ./services/admin
    environment:
      - MSSQL_HOST=mssql
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_DB=AdventureWorks
      - MSSQL_PORT=1433

      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME_ADMIN}
      - PORT=3003
    volumes:
      - ./services/shared:/app/shared:ro
    ports:
      - "${ADMIN_CONSOLE_PORT}:3003"
    networks:
      - frontend
      - backend
    depends_on:
      mssql:
        condition: service_healthy

  hr:
    build:
      context: ./services/hr
    environment:
      - MSSQL_HOST=mssql
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_DB=AdventureWorks
      - MSSQL_PORT=1433

      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME_HR}
      - PORT=3000
    volumes:
      - ./services/shared:/app/shared:ro
    ports:
      - "${HR_PORTAL_PORT}:3000"
    networks:
      - frontend
      - backend
    depends_on:
      mssql:
        condition: service_healthy

  payroll:
    build:
      context: ./services/payroll
    environment:
      - MSSQL_HOST=mssql
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_DB=AdventureWorks
      - MSSQL_PORT=1433

      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME_PAYROLL}
      - PORT=3001
    volumes:
      - ./services/shared:/app/shared:ro
    ports:
      - "${PAYROLL_SYSTEM_PORT}:3001"
    networks:
      - frontend
      - backend
    depends_on:
      mssql:
        condition: service_healthy

  performance:
    build:
      context: ./services/performance
    environment:
      - MSSQL_HOST=mssql
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_DB=AdventureWorks
      - MSSQL_PORT=1433

      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME_PERFORMANCE}
      - PORT=3002
    volumes:
      - ./services/shared:/app/shared:ro
    ports:
      - "${PERFORMANCE_REVIEW_PORT}:3002"
    networks:
      - frontend
      - backend
    depends_on:
      mssql:
        condition: service_healthy

  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6/scripts:/scripts
    environment:
      - HR_PORTAL_URL=${HR_PORTAL_URL}
      - PAYROLL_SYSTEM_URL=${PAYROLL_SYSTEM_URL}
      - PERFORMANCE_REVIEW_URL=${PERFORMANCE_REVIEW_URL}
      - ADMIN_CONSOLE_URL=${ADMIN_CONSOLE_URL}
    networks:
      - frontend
    depends_on:
      - hr
      - payroll
      - performance
      - admin

networks:
  frontend:
  backend:

volumes:
  sqldata:
