[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:mysql]
command=/usr/local/bin/docker-entrypoint.sh mysqld
user=mysql
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/mysql.log
stderr_logfile=/var/log/supervisor/mysql.err
priority=10

[program:newrelic-infra]
command=/usr/local/newrelic-infra/bin/newrelic-infra
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/newrelic.log
stderr_logfile=/var/log/supervisor/newrelic.err
priority=20
startsecs=10